baseurl: "/Quelea"
pldiurl: "http://gowthamk.github.io/docs/quelea.pdf"
vmurl: "https://www.dropbox.com/s/dd1nzms16ihlggl/Quelea.ova?dl=0"
tarurl: "https://www.cs.purdue.edu/sss/projects/quelea/quelea-oss.tar.gz"
